
package descargados;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InterServer", targetNamespace = "http://webServices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InterServer {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDirectorio", targetNamespace = "http://webServices/", className = "descargados.GetDirectorio")
    @ResponseWrapper(localName = "getDirectorioResponse", targetNamespace = "http://webServices/", className = "descargados.GetDirectorioResponse")
    @Action(input = "http://webServices/InterServer/getDirectorioRequest", output = "http://webServices/InterServer/getDirectorioResponse")
    public String getDirectorio();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMensaje", targetNamespace = "http://webServices/", className = "descargados.GetMensaje")
    @ResponseWrapper(localName = "getMensajeResponse", targetNamespace = "http://webServices/", className = "descargados.GetMensajeResponse")
    @Action(input = "http://webServices/InterServer/getMensajeRequest", output = "http://webServices/InterServer/getMensajeResponse")
    public String getMensaje();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListaHuellas", targetNamespace = "http://webServices/", className = "descargados.GetListaHuellas")
    @ResponseWrapper(localName = "getListaHuellasResponse", targetNamespace = "http://webServices/", className = "descargados.GetListaHuellasResponse")
    @Action(input = "http://webServices/InterServer/getListaHuellasRequest", output = "http://webServices/InterServer/getListaHuellasResponse")
    public List<String> getListaHuellas();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "guardarHuella", targetNamespace = "http://webServices/", className = "descargados.GuardarHuella")
    @ResponseWrapper(localName = "guardarHuellaResponse", targetNamespace = "http://webServices/", className = "descargados.GuardarHuellaResponse")
    @Action(input = "http://webServices/InterServer/guardarHuellaRequest", output = "http://webServices/InterServer/guardarHuellaResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webServices/InterServer/guardarHuella/Fault/Exception")
    })
    public int guardarHuella(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "identificarHuella", targetNamespace = "http://webServices/", className = "descargados.IdentificarHuella")
    @ResponseWrapper(localName = "identificarHuellaResponse", targetNamespace = "http://webServices/", className = "descargados.IdentificarHuellaResponse")
    @Action(input = "http://webServices/InterServer/identificarHuellaRequest", output = "http://webServices/InterServer/identificarHuellaResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://webServices/InterServer/identificarHuella/Fault/Exception")
    })
    public String identificarHuella(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0)
        throws Exception_Exception
    ;

}
