
package descargados;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InterServerImpService", targetNamespace = "http://webServices/", wsdlLocation = "http://192.168.10.149:8080/ejemploHuellaWS?wsdl")
public class InterServerImpService
    extends Service
{

    private final static URL INTERSERVERIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException INTERSERVERIMPSERVICE_EXCEPTION;
    private final static QName INTERSERVERIMPSERVICE_QNAME = new QName("http://webServices/", "InterServerImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.10.149:8080/ejemploHuellaWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INTERSERVERIMPSERVICE_WSDL_LOCATION = url;
        INTERSERVERIMPSERVICE_EXCEPTION = e;
    }

    public InterServerImpService() {
        super(__getWsdlLocation(), INTERSERVERIMPSERVICE_QNAME);
    }

    public InterServerImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INTERSERVERIMPSERVICE_QNAME, features);
    }

    public InterServerImpService(URL wsdlLocation) {
        super(wsdlLocation, INTERSERVERIMPSERVICE_QNAME);
    }

    public InterServerImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INTERSERVERIMPSERVICE_QNAME, features);
    }

    public InterServerImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InterServerImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InterServer
     */
    @WebEndpoint(name = "InterServerImpPort")
    public InterServer getInterServerImpPort() {
        return super.getPort(new QName("http://webServices/", "InterServerImpPort"), InterServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterServer
     */
    @WebEndpoint(name = "InterServerImpPort")
    public InterServer getInterServerImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webServices/", "InterServerImpPort"), InterServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INTERSERVERIMPSERVICE_EXCEPTION!= null) {
            throw INTERSERVERIMPSERVICE_EXCEPTION;
        }
        return INTERSERVERIMPSERVICE_WSDL_LOCATION;
    }

}
